### ISSUE TITLE
How to create a shared link

### ISSUE THREAD

**Issue by clthck** [kunalvarma05/dropbox-php-sdk#1]
I couldn't find out any method that allows me to create a shared link. Is there any solution to this?

**Comment by kunalvarma05** [comment]
Currently the SDK covers the **auth**, **files** & **users** endpoints. Will start implementing the **sharing** endpoints soon. For now, you can try creating a shared link this way:

```php
/**
* Assuming you have configured the DropboxApp class
* @see https://github.com/kunalvarma05/dropbox-php-sdk/wiki/Configuration
*/
$dropbox = new Dropbox($app);
$response = $dropbox->postToAPI("/sharing/create_shared_link_with_settings", ["path" => "/hello-world.txt", "settings" => ['requested_visibility' => 'public']]);

$data = $response->getDecodedBody();
var_dump($data);
```

**Comment by clthck** [comment]
It works, thanks

**Comment by ogwugo** [comment]
can this be used to get permanent link?
