### ISSUE TITLE
installation fails

### ISSUE THREAD

**Issue by AllegroBarry** [kunalvarma05/dropbox-php-sdk#10]
Hello, I'm trying to install your dropbox api, and I get the following error:

fuji:photos root# $PHP7 composer.phar require kunalvarma05/dropbox-php-sdk
Using version ^0.1.1 for kunalvarma05/dropbox-php-sdk
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing tightenco/collect (v5.3.4)
    Downloading: 100%         

Installation failed, deleting ./composer.json.

                                                                                                                       
  [ErrorException]                                                                                                     
  copy(/santa/home/Allegro/customers/Frantz/photos/vendor/composer/7776a799/tightenco-collect-66022ef/._.gitignore):   
  failed to open stream: No such file or directory                                                                     
                                                                                                                       

require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--] [<packages>]...

fuji:photos root#

**Comment by AllegroBarry** [comment]
FYI, I tried again with PHP 5.6 instead of PHP 7 and got the same error:


fuji:photos root# $PHP5 composer.phar require kunalvarma05/dropbox-php-sdk
Using version ^0.1.1 for kunalvarma05/dropbox-php-sdk
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing tightenco/collect (v5.3.4)
    Loading from cache

Installation failed, reverting ./composer.json to its original content.

                                                                                                                       
  [ErrorException]                                                                                                     
  copy(/santa/home/Allegro/customers/Frantz/photos/vendor/composer/e82530a2/tightenco-collect-66022ef/._.gitignore):   
  failed to open stream: No such file or directory                                                                     
                                                                                                                       

require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--] [<packages>]...

fuji:photos root#

**Comment by kunalvarma05** [comment]
@AllegroBarry It doesn't seem to be an issue regarding PHP. Is your Composer up-to-date?

The [Composer folks](https://github.com/composer/composer) would be better at handling this.

Thanks.
