### ISSUE TITLE
Use this in codeigniter

### ISSUE THREAD

**Issue by netdeveloper1job** [kunalvarma05/dropbox-php-sdk#106]
Hi can you please guide me how i call this api usi codeigniter framwork

**Comment by marcus-at-localhorst** [comment]
There is plenty of information how to include third-party libraries in Codeigniter.
As a start: https://stackoverflow.com/questions/45009712/load-external-library-in-codeigniter

**Comment by netdeveloper1job** [comment]
classes are not load due to namespace.
any alternate to use namespace in CI framework or any version of this library without  namespace ?

**Comment by netdeveloper1job** [comment]
I also checked with removing namespaces from all files . But still I getting 
"Unable to locate the specified class: Session.php" in my controller.

**Comment by raenk** [comment]
With composer is pretty easy. Install the SDK with composer, make sure the autoload is set to TRUE in config.php and then set the namespaces before the class begins in your controller:

`use Kunnu\Dropbox\Dropbox;
use Kunnu\Dropbox\DropboxApp;
use Kunnu\Dropbox\DropboxFile;`
