### ISSUE TITLE
Overwirte file with 'saveUrl'

### ISSUE THREAD

**Issue by raenk** [kunalvarma05/dropbox-php-sdk#110]
I need to overwrite files with this method. Is it possible? How? Thanks!

**Comment by kunalvarma05** [comment]
According to [Dropbox's API Documentation](https://www.dropbox.com/developers/documentation/http/documentation#files-save_url), it's currently not possible.

The default and only behavior is: 
> ...If the given path already exists, the file will be renamed to avoid the conflict (e.g. myfile (1).txt).
