### ISSUE TITLE
localhost authentication error without SSL

### ISSUE THREAD

**Issue by asimakos** [kunalvarma05/dropbox-php-sdk#113]
Congrats for your great and updated dropbox php sdk!

I am trying to be authenticated in a localhost development environment without SSL. Is that possible or not as i get the error on the following code:
$callbackUrl = "http://localhost/dropboxphp/finish.php";

$accessToken = $authHelper->getAccessToken($code, $state, $callbackUrl);
echo $accessToken->getToken();

![dropbox](https://user-images.githubusercontent.com/15226087/35873143-8ba90500-0b71-11e8-8b63-42f37614fc04.jpg)

I might need further help later as it is my first experience with Dropbox v2 API. This is really educative but it's for API v1 ONLY (unfortunately deprecated now) https://www.youtube.com/watch?v=FsQZyNpDWv0.  

Regards

**Comment by asimakos** [comment]
Finally i did the following in order to work successfully which is not mentioned for those who use WAMP or other similar packages.
That's is very important to be mentioned even for [localhost development](https://stackoverflow.com/questions/28858351/php-ssl-certificate-error-unable-to-get-local-issuer-certificate).

Regards

**Comment by 0x2f0713** [comment]
I have the same issue. Thank you so much!
