### ISSUE TITLE
I am not able to upload file from local to dropbox

### ISSUE THREAD

**Issue by samumaretiya** [kunalvarma05/dropbox-php-sdk#114]
Hi there,

I am successfully connected to drop box using your sdk in php but i am not able to upload my file to drop box.

Here is the code snippet 

`<?php
ini_set('display_errors',1);

session_start();

require_once 'dropbox-php-sdk/vendor/autoload.php';

use Kunnu\Dropbox\Dropbox;
use Kunnu\Dropbox\DropboxApp;

$app = new DropboxApp("vsz2ag6blsai4ru", "xt8s0w87dqt9ure","ApfiLRe59gAAAAAAAAAARSxfcR_263pVxQ_SvkHlhVEy_uKXfSOP5Wu9XPVkJBMu");

$dropbox = new Dropbox($app);

/* $callbackUrl = "http://localhost/magento1934/";
$authHelper = $dropbox->getAuthHelper();
$authUrl    = $authHelper->getAuthUrl($callbackUrl);
*/

use Kunnu\Dropbox\DropboxFile;
try
{
	$pathToLocalFile =  "firstupload.txt";
	$dropboxFile = DropboxFile::createByStream("firstupload.txt", $pathToLocalFile);
	$file = $dropbox->upload($dropboxFile, "test/firstupload.txt", ['autorename' => true]);
	echo $file->getName();
}
catch(Exception $e)
{
	echo $e->getMessage();
}
?>` 

Could you please look into the issue and let me know where I need to correct code.

Regards,

Sam

**Comment by kunalvarma05** [comment]
Unfortunately, I'm unable to reproduce this issue on my end. Feel free to reopen this issue along with the exception/error message if the problem still persists.
