### ISSUE TITLE
json encode return empty array

### ISSUE THREAD

**Issue by TendiF** [kunalvarma05/dropbox-php-sdk#116]
$listFolderContents = $this->dropbox->listFolder("/");
//Fetch Items (Returns an instance of ModelCollection)
$items = $listFolderContents->getItems();
//All Items
$items = $items->all();

return $items;

**Comment by kunalvarma05** [comment]
See https://github.com/kunalvarma05/dropbox-php-sdk/issues/157#issuecomment-571388125
