### ISSUE TITLE
Parameters in ChunkedFileUpload not working

### ISSUE THREAD

**Issue by JSchmidt1909** [kunalvarma05/dropbox-php-sdk#12]
The Dropbox parameters for uploading are not working with ChunkedFileUpload. I think, you just forgot to pass the parameters to the `finishUploadSession`-Method in Line 1007 in Dropbox.php. It should be:

`return $this->finishUploadSession($dropboxFile, $sessionId, $uploaded, $remaining, $path, $params);`

**Comment by kunalvarma05** [comment]
@JSchmidt1909 Thanks for pointing out!

**Comment by Cheecherngho799** [comment]
http://asean.org/subscribe/?wpmlmethod=optin#newsletters-embed6832
