### ISSUE TITLE
Invalid Response

### ISSUE THREAD

**Issue by DangerD256** [kunalvarma05/dropbox-php-sdk#13]
Trying to download file:
```
<?php
include('../inc/vendor/autoload.php');
use Kunnu\Dropbox\Dropbox;
use Kunnu\Dropbox\DropboxApp;

$app = new DropboxApp(key, secret, access token generated in my apps);
$dropbox = new Dropbox($app);
$file = $dropbox->download("/Book1.xlsx");

//File Contents
echo $contents = $file->getContents();
```
And getting error:
PHP Fatal error:  Uncaught exception 'Kunnu\Dropbox\Exceptions\DropboxClientException' with message 'Invalid Response'
...
/DropboxClient.php(163): Kunnu\Dropbox\DropboxResponse->__construct(Object(Kunnu\Dropbox\DropboxRequest), 'PK\x03\x04\x14\x00\x06\x00\x08\x00\x00\x00!\x00\xA7...', 200, Array)

How can i check what exact error i'm receving (maybe bad token or something else)?
Note: PK\x03\x04\ is the start if binary file, so script downloads file but some error occurs...

P.S. $dropbox->getMetadata("/Book1.xlsx"); works fine and receives info

**Comment by DangerD256** [comment]
Found an issue, when downloading file script tries to do json_decode on binary file:
`$this->decodedBody = json_decode((string) $body, true);`

**Comment by DangerD256** [comment]
That quick fix helped:
```
		if($this->decodedBody=== null && $body!='')
			$this->decodedBody = array('file'=>$body);
```
Not a solution, but works

**Comment by danielholmes** [comment]
Current solution I'm using is (this replaces the current decodeBody method in DropboxResponse):

```
protected function decodeBody()
    {
        $body = $this->getBody();

        if (isset($this->headers['Content-Type']) && $this->headers['Content-Type'] === 'application/json') {
            $this->decodedBody = json_decode((string)$body, true);
        } else {
            $this->decodedBody = $this->body;
        }

        // If the response needs to be validated
        if ($this->getRequest()->validateResponse()) {
            //Validate Response
            $this->validateResponse();
        }
    }
```

**Comment by kunalvarma05** [comment]
Thanks @DangerD256 and @danielholmes !
