### ISSUE TITLE
cURL error 60

### ISSUE THREAD

**Issue by maexen** [kunalvarma05/dropbox-php-sdk#148]
this is the extended error:
_Uncaught Kunnu\Dropbox\Exceptions\DropboxClientException: cURL error 60: Peer's Certificate issuer is not recognized. (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)_

our server uses a Let's Encrypt certificate
could this be the reason?
Unfortunately I can't say for sure if Let's Encrypt is SSL or TLS.

To temporarily solve the problem I modified the file:
dropbox-2-k/vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php

from:
$conf[CURLOPT_SSL_VERIFYHOST] = 2;
$conf[CURLOPT_SSL_VERIFYPEER] = true;

to:
$conf[CURLOPT_SSL_VERIFYHOST] = 0;
$conf[CURLOPT_SSL_VERIFYPEER] = FALSE;

in this way I excluded the control on the certificate.
Thanks for any suggestions.

**Comment by matteobaccan** [comment]
Hi

you can also create a GuzzleClient without SLL verification

$guzzleClient = new \GuzzleHttp\Client(array( 'curl' => array( CURLOPT_SSL_VERIFYPEER => false, ), ));

and use it when initiziali DropBox
    
$dropbox = new Dropbox($app, ['http_client_handler' => $guzzleClient] );

all the best
matteo baccan

**Comment by shivapoudel** [comment]
This issue is basically found in Local by Flywheel for me, I tried to resolve like this.

```php
$guzzleClient = new \GuzzleHttp\Client(
	array(
		'verify' => false, // Otherwise HTTPS requests will fail.
	)
);
```

And then while configuring Dropbox service, used like this.

```php
// Configure Dropbox application.
$app = new DropboxApp( 'client_id', 'client_secret', 'access_token' );

// Configure Dropbox service.
$dropbox = new Dropbox( $app, array( 'http_client_handler' => $guzzleClient ) );
```
