### ISSUE TITLE
List Folders files

### ISSUE THREAD

**Issue by SitpiRajendran** [kunalvarma05/dropbox-php-sdk#150]
Hi guys,

First thanks Kunal for this sdk it's very useful !

I have a problems : i don't understant how list all files name of a folder, with the wiki (https://github.com/kunalvarma05/dropbox-php-sdk/wiki/Working-with-files), but i don"t understand :

```
$listFolderContents = $dropbox->listFolder("/VNHTVEFLZ");

$items = $listFolderContents->getItems();

$first = $items->first();
$name = $first->getName();

echo($name.' + ');
if ($items->hasMoreItems()) {
    echo('(enter)');
    $cursor = $items->getCursor();
    $listFolderContinue = $dropbox->listFolderContinue($cursor);
    $remainingItems = $listFolderContinue->getItems();
    $first = $remainingItems->first();
    $name = $first->getName();
}
```

My program never enter in the if , but there is other files then the first one.

Thanks in advance,

**Comment by dval** [comment]
It's possible that you don't have enough items to trigger pagination. `hasMoreItems()` only returns items if there is more than 25 or 50? whatever the default dropbox setting is.  So, if your folder only has 12 items in it, they will all be in the `getItems()` return.  

Once the first page is 'full', then `hasMoreItems()` will return true and subsequent calls to `getItems()` will contain the files of those pages.

**Comment by lachlan-00** [comment]
Ah HA!, thank you for this. That explains this issue i'm loking at

https://github.com/ampache/ampache/issues/2264

**Comment by lachlan-00** [comment]
Thanks for posting this issue it's really helped me understand this.
Now can do some testing on that and i can report back what the getitems limit is.

I'm assuming the process would be
* getitems
* loop through items list
* if hasmoreitems
  * getcursor
  * listfoldercontinue from cursor
  * getitems from listfoldercontinue
  * loop your new list
  * repeat until not hasmoreitems.
