### ISSUE TITLE
listFolder() returns empty json objects

### ISSUE THREAD

**Issue by dval** [kunalvarma05/dropbox-php-sdk#157]
using:

    try{
        $listFolderContents = $this->dropbox->listFolder( "" );
        $items = $listFolderContents->getItems();
        echo json_encode($items);
    } catch (DropboxClientException $e) {
        echo json_encode($e);
    }

the return is: `[{},{},{}]`.  

That is one blank object for each folder in the app.  If I call with recursive set to true, I get six blank objects. ( Each folder has 1 image in it. )

    $listFolderContents = $this->dropbox->listFolder( "" ,[ "recursive" => true]);
    $items = $listFolderContents->getItems();
    echo json_encode($items);

the return is: `[{},{},{},{},{},{}]`.  

However, if I call the API directly I can see the expected result of the list of folders.

    $response = $dropbox->postToAPI("/files/list_folder", ["path" => "" ]);
    $items = $response->getDecodedBody();
    echo json_encode($items);

The result is the list of the 3 folders:

```
{
  "entries": [
    {
      ".tag": "folder",
      "name": "concept",
      "path_lower": "/concept",
      "path_display": "/concept",
      "id": "id:1xxxxxxxxxxxxAxxxxw"
    },
    {
      ".tag": "folder",
      "name": "project",
      "path_lower": "/project",
      "path_display": "/project",
      "id": "id:1xxxxxxxxxxxxAxxxA"
    },
    {
      ".tag": "folder",
      "name": "working",
      "path_lower": "/working",
      "path_display": "/working",
      "id": "id:1xxxxxxxxxxAxxxQ"
    }
  ],
  "cursor": "AAH74...x64....sx_pHsQ",
  "has_more": false
}

```
Installed with composer, using php 7.2
Currently, there are no php errors in the server logs. 

Possibly related: #150, #116 

Less likely related: #90

**Comment by slightlydiff** [comment]
Thanks for you email.

I'm away until Friday 24th January.  

For any hosting support issues please submit a ticket via https://my.slightlydifferent.co.nz/

For all other matters please raise a ticket if urgent only. Otherwise I will get back to you as soon as possible on my return.

Kind regards

Steve

**Comment by dval** [comment]
Ok, I figured it out. 
The result of getItems() is not serializable. I had to call getData() for each item in that list. 
The following works:

```
$listFolderContents = $this->dropbox->listFolder( "" );
$items = $listFolderContents->getItems();
$itemData = array();
foreach ($items as $key => $value) {
    $itemData[$key] = $value->getData();
}
echo json_encode($itemData);
```

and it returns similar structure as above.

```
[
    {
      ".tag": "folder",
      "name": "concept",
      "path_lower": "/concept",
      "path_display": "/concept",
      "id": "id:1xxxxxxxxxxxxAxxxxw"
    },
    {
      ".tag": "folder",
      "name": "project",
      "path_lower": "/project",
      "path_display": "/project",
      "id": "id:1xxxxxxxxxxxxAxxxA"
    },
    {
      ".tag": "folder",
      "name": "working",
      "path_lower": "/working",
      "path_display": "/working",
      "id": "id:1xxxxxxxxxxAxxxQ"
    }
  ]
```
