### ISSUE TITLE
Waiting for [Working with Shared links and Shared Folder]

### ISSUE THREAD

**Issue by dobaniashish** [kunalvarma05/dropbox-php-sdk#16]
Hello,

I am using you sdk to communicate with dropbox.
After uploading the file I am making a custom api call to get sharable link by using "sharing/create_shared_link_with_settings".

I want to make everything work with this library so waitong for that. Any updates on progress of this?

Thank You,
Ashish Dobani.

**Comment by kunalvarma05** [comment]
@dobaniashish In progress. Would update shortly.

Thanks.
