### ISSUE TITLE
Getting this Error

### ISSUE THREAD

**Issue by sitestrokes** [kunalvarma05/dropbox-php-sdk#163]
PHP Parse error:  syntax error, unexpected '->' (T_OBJECT_OPERATOR) in dropbox/vendor/tightenco/collect/src/Collect/Support/Collection.php on line 179

Please help Thanks

**Comment by Nahuelvvn** [comment]
Did you check the PHP version on your server? I faced the same issue when updating 7.1 to 7.3, solved by rolling back.
