### ISSUE TITLE
Better explanation of thrown exception?

### ISSUE THREAD

**Issue by SneakyDave** [kunalvarma05/dropbox-php-sdk#17]
I assume that this is a connectivity issue with DropBox, but sometimes, an addon I developed using this library will throw: 
```
Kunnu\Dropbox\Exceptions\DropboxClientException: - xxxx/vendor/kunalvarma05/dropbox-php-sdk/src/Dropbox/Http/Clients/DropboxGuzzleHttpClient.php:67
```
But there isn't a good explanation. 

Is that because the output of the error message would come from the $rawResponse?
```
throw new DropboxClientException($rawResponse->getBody());
```

**Comment by SneakyDave** [comment]
I probably just need a way to get the $rawResponse I think.

I'm using this code to upload a file
'''
$result = $dropbox->upload($dropboxFile,$dropboxDir.$uploadname);
'''
And the error is thrown in the send method (obviously). But would the $rawReponse be available in the $result if the send() method fails?

**Comment by kunalvarma05** [comment]
@SneakyDave I tried reproducing the bug, but the exception being thrown contains an error message at all times. However, the error message depends on the type of the error (https://www.dropbox.com/developers/documentation/http/documentation#error-handling). Therefore, I might need more information to reproduce the bug.

What error/exception message and response code are you being shown when calling the `upload()` method fails? Can you try and reproduce this bug with the following code:

```php
$file = __DIR__ . "/hello.txt"; // Replace this with a path to an existing file
try {
   // Upload the file with an invalid mode. Valid modes are: add, overwrite and update
    var_dump($dropbox->upload($file, "/hello.txt", ['mode' => 'invalid-mode']));
} catch (Exception $e) {
    echo $e->getMessage();
}
```
This should show the following error message: 
`Error in call to API function "files/upload": HTTP header "Dropbox-API-Arg": mode: unknown tag 'invalid-mode'`

Thanks.

**Comment by SneakyDave** [comment]
It isn't a consistent error. It's part of an addon I wrote for XenForo that uploads a backup file of a XenForo installation to DropBox, and users of the addon have reported that once in a while, using the addon will return an error from the GuzzleHttpClient on the upload method:
https://xenforo.com/community/threads/solidmean-forumbackup-dropbox-upload-paid.102856/page-4#post-1093298

I was just curious if there was a way to better trap the error message, because right now, it just throws the exception.
