### ISSUE TITLE
guzzle 7 support?

### ISSUE THREAD

**Issue by mdfUK** [kunalvarma05/dropbox-php-sdk#172]
Are there any plans to support guzzle 7 - I have a project where that is a dependency of another package & would like to use your package too but only supports up to guzzle 6 . . .
Thanks ;-)

**Comment by mdfUK** [comment]
Found a workaround - would still be interested though

**Comment by afagard** [comment]
@mdfUK what was your workaround?

**Comment by mdfUK** [comment]
> @mdfUK what was your workaround?

Turned out the other package _preferred_ guzzle 7 but would work with guzzle 6 so I just downgraded to guzzle 6

Not particularly elegant but it works ;-)
