### ISSUE TITLE
problem Dropbox-API-Select-User

### ISSUE THREAD

**Issue by Fxer0x** [kunalvarma05/dropbox-php-sdk#173]
Message: Error in call to API function "files/download": This API function operates on a single Dropbox account, but the OAuth 2 access token you provided is for an entire Dropbox Business team. Since your API app key has team member file access permissions, you can operate on a team member's Dropbox by providing the "Dropbox-API-Select-User" HTTP header or "select_user" URL parameter to specify the exact user .

my code:
$dropbox = new Dropbox($app);
$name="410-3-1.jpg";
$file=$dropbox->download("/prod/410-3/".$name);
//File Contents
$contents=$file->getContents();
//Save file contents to disk
file_put_contents("img/prod/410-3/".$name, $contents);

I need help, I can't reference the Dropbox-API-Select-User or include the header.

**Comment by amf-paulinho** [comment]
This is so upsetting, it does not matter the SDK, in my case .NET, but I also saw the same question for phyton, for javascript. The Dropbox team basically ignores it.
I am trying something that should be simple. Create a folder and share it with a specific email. Crazy confusing messages, never work, documentation is broken, dropbox forum always answers 404 error.
