### ISSUE TITLE
Is it in plan to implement short-lived auth tokens?

### ISSUE THREAD

**Issue by tilekus** [kunalvarma05/dropbox-php-sdk#182]
As you know on September 30th 2021 long-lived access token will be deprecated. [https://dropbox.tech/developers/migrating-app-permissions-and-access-tokens](url).
So my question is - will you update sdk to work with short-lived access token?
Thank you

**Comment by jokamax** [comment]
+1 is there a chance to see this lib updated ?

**Comment by brandonobrien** [comment]
This would be a great upgrade since they're getting rid of the long lived tokens in about a month.  I'd hate to have to update my code to switch to a different SDK but it's looking like that might be the case.  This project hasn't seen an update in nearly 4 years which doesn't give me much hope.

**Comment by jokamax** [comment]
Thanks @brandonobrien I will try to do that next week.
Can I reply here if I have a question ?

**Comment by brandonobrien** [comment]
> Thanks @brandonobrien I will try to do that next week.
> Can I reply here if I have a question ?

Definitely.  Just reply or @ me and I should see it.

**Comment by jokamax** [comment]
@brandonobrien 

1. When I use getToken() -> 'refresh_token' => $this->refreshToken,
The "$this->refreshToken" is the previous : $token_data = $accessToken->getData(); ???

2. Each time I get a new refreshToken : I have to store it again to use it in the next getToken() ?

3.
(getDropBoxShortTokenFromPreviousRefreshToken -> is my getToken with a parameter)
$newShortLiveToken = StorageHelper::getDropBoxShortTokenFromPreviousRefreshToken($oldShortLiveToken);
$dropbox->setAccessToken($newShortLiveToken ); 
$dropbox->createFolder("/" . $arrDataToExport[3]);

2021-10-10 12:46:54 [77.139.35.126][1][r05c2ikvqhvb93qrnnp4iv5l5a][error][application] Error - Dropbox upload : Error in call to API function "files/create_folder": The given OAuth 2 access token is malformed.

Do you see where I made a mistake ??

thanks
