### ISSUE TITLE
Error: Call to undefined function GuzzleHttp\Psr7\stream_for() and php 8.1

### ISSUE THREAD

**Issue by reimax** [kunalvarma05/dropbox-php-sdk#189]
after switching to php 8.1, an attempt to upload file, i get error
Error: Call to undefined function GuzzleHttp\Psr7\stream_for() 
 
in composer.json i add "guzzlehttp/psr7": "^1.8.2"
and uploads work

if in composer add last version guzzlehttp/psr7 the error appears again

**Comment by stccorp** [comment]
I was having the same error. I did what you suggested and it fixed my problem. I am using php 7.4

**Comment by g19i85g** [comment]
I have the same Problem.

**Comment by thyseus** [comment]
Temporary solutions available at: https://github.com/kunalvarma05/dropbox-php-sdk/issues/192

**Comment by phil-davis** [comment]
And PR #195 is waiting for review, merge, release.
