### ISSUE TITLE
Check if object is file or folder

### ISSUE THREAD

**Issue by unlikenesses** [kunalvarma05/dropbox-php-sdk#19]
Is there a way to check if an object is a file or a folder? E.g. I get my folder content with `$folder_content->getItems()`. For each `$item`, I can access the `$item->name`, `$item->path_lower`, etc. But when I try to access `$item->data` (which includes the `.tag` property, which seems to be either `folder` or `file`), I get null. Anyone else had dealings with this issue?

**Comment by kunalvarma05** [comment]
All the Models (FileMetadata, FolderMetadata, etc) extend the BaseModel, which contains the `getData()` method.

The `getData()` method returns an array which would give you access to the `.tag` you're looking for. Additionally, there is also a `getDataProperty()` method which takes a single key as a parameter to return the value of the key from the data array. You can always refer to the API Docs. 

In your case, this is how it would work:

```php
$items = $folder_contents->getItems();

foreach ($items as $item){
    $isFile=$item->getData()['.tag']==='file';
    // OR
    $isFile=$item->getDataProperty('.tag')==='file';

    if($isFile){
    // File
    }else{
    // Folder
    }
}
```
