### ISSUE TITLE
tightenco/collect is backdated

### ISSUE THREAD

**Issue by ashickur-rahman** [kunalvarma05/dropbox-php-sdk#190]
this package require tightenco/collect 5.2 but few of it's method is dedicated in php 8. Please update it.

**Comment by Positic** [comment]
UP!! Please, change version of tightenco/collect

**Comment by ngandemeratslsy** [comment]
UP !!!
It seems this package is not used anymore in your source code, instead you reference Illuminate\Support\Collection in ModelCollection, but no require on illuminate/support in your composer.json founded
