### ISSUE TITLE
Short-lived Access Token and Refresh Token , HOW TO DO IT?

### ISSUE THREAD

**Issue by stccorp** [kunalvarma05/dropbox-php-sdk#202]
The first time I get a token I get and object Kunnu\Dropbox\Models\AccessToken 

Then I call $accessToken->getToken(), which returns a string

I save that string for later.  

I dont know how to get a token object from the string token so I can check if is expired or not ?

//I would expect something like 
//IMAGININARY CODE, HOW IS I REALLY DONE?????
$app = new DropboxApp("XXX", "XXX");
$dropbox= new Dropbox($app);
$dropbox->setAccessToken($saved_token_string_from_the_past);

$token_object = $dropbox->getTokenObject();
if ($token_object->expired()){
       $authHelper = $dropbox->getAuthHelper();
       $new_refreshed_token_object = $authHelper->getRefreshedAccessToken($token_object);
       $token_string_to_save_for_future = $new_refreshed_token_object->getToken();
}

getRefreshedAccessToken  expect and object that I DONT have,  I only have the string access token

Thank you

**Comment by stccorp** [comment]
for anyone wanting to do this. I came up with an answer that may or may not be the correct one

 $token = $authHelper->getAccessToken($code, $state, $callbackUrl);

    $token_data = [
        'access_token' => $token->getDataProperty('access_token')
        , 'token_type' => $token->getDataProperty('token_type')
        , 'bearer' => $token->getDataProperty('bearer')
        , 'uid' => $token->getDataProperty('uid')
        , 'account_id' => $token->getDataProperty('account_id')
        , 'team_id' => $token->getDataProperty('team_id')
        , 'expires_in' => $token->getDataProperty('expires_in')
        , 'refresh_token' => $token->getDataProperty('refresh_token')];

Then just save the json_encode( $token_data)


Then 
$access_token = new AccessToken(json_decode($token_data,true));

The only problem is that the expiration time in not real BUT easy fixed saving the time when it was created


Seems like at lot of work, must likely there is a better way

**Comment by sunilit42** [comment]
Is there any solution how to get new tocken?
