### ISSUE TITLE
Getting exception when revoking access token

### ISSUE THREAD

**Issue by taduuda** [kunalvarma05/dropbox-php-sdk#21]
Hi,

I'm using the code below to revoke access tokens, but I always get a Dropbox\Exceptions\DropboxClientException with message 'Invalid Response' (thus the if-statement in the catch). 
```
try {
  $app = new Dropbox\DropboxApp($dropbox_app_id,$dropbox_app_sec,$user_access_token);
  $dropbox = new Dropbox\Dropbox($app);
  $authHelper = $dropbox->getAuthHelper();
  $authHelper->revokeAccessToken();
} catch (Dropbox\Exceptions\DropboxClientException $e) {
  if ($e->getMessage() == 'Invalid Response') {
      echo 'Token revoked';
  }
}
```

The revoke works fine, I was just wondering whether there is a way to revoke the token without getting the exception. Here is what I found:
The exception gets thrown as the response is validated. According to the [official documentation](https://www.dropbox.com/developers/documentation/http/documentation#auth-token-revoke) revoking a token does not return anything. Since the validate function is built to throw the exception if the decodedBody of the response is null, the exception will always get thrown when revoking a token.

So, we'd need to pass something like a $isRevokeRequest parameter to the validateResponse function in order to not get the exception.

Cheers,
-Taduuda

**Comment by kunalvarma05** [comment]
@taduuda This has been fixed. All it needed, was to set `validateResponse` param to be set to `false`, for the [`DropboxResponse`](../blob/master/src/Dropbox/DropboxResponse.php) class to [**not** validate the response](../blob/master/src/Dropbox/DropboxResponse.php#L142), which has been fixed [here](../blob/8f5a147bbe29a0c6ac4db465b74ebb1ab18f0a68/src/Dropbox/Authentication/OAuth2Client.php#L176).

Thanks for reporting!
