### ISSUE TITLE
PersistentDataStoreFactory - wrong interface name ?

### ISSUE THREAD

**Issue by tomblakemore** [kunalvarma05/dropbox-php-sdk#22]
I believe lines 29-31 should be:

```
if ($store instanceof PersistentDataStoreInterface) {
    return $store;
}
```

Master branch has `PersistentDataInterface` rather than `PersistentDataStoreInterface`.

**Comment by kunalvarma05** [comment]
Actually, the Master has the fixed version. However, there doesn't seem to be a tagged version of this fix.

Thanks.
