### ISSUE TITLE
Missing get temporary link 

### ISSUE THREAD

**Issue by sharksoft** [kunalvarma05/dropbox-php-sdk#23]
HI, can you add che get temporary link (https://www.dropbox.com/developers/documentation/http/documentation#files-get_temporary_link) api request?

**Comment by kunalvarma05** [comment]
Hey, the SDK already has it. [`getTemporaryLink`](https://github.com/kunalvarma05/dropbox-php-sdk/wiki/Working-with-files#get-temporary-link).
