### ISSUE TITLE
createFolder() function should allow parameters

### ISSUE THREAD

**Issue by jmrieger** [kunalvarma05/dropbox-php-sdk#25]
According to the most recent Dropbox API:
https://www.dropbox.com/developers/documentation/http/documentation#files-create_folder

The create_folder endpoint should allow both the path and autorename parameters. Path is figured automatically in your code, but there's no option for autorename.

**Comment by kunalvarma05** [comment]
[This commit](https://github.com/kunalvarma05/dropbox-php-sdk/commit/f39cf3bdd7d7ed75c678504646a01a79d95e729d) closes the issue.

Thanks :)
