### ISSUE TITLE
Check file exists before remove

### ISSUE THREAD

**Issue by reimax** [kunalvarma05/dropbox-php-sdk#26]
Hi,
I need to do a background check on suschestvoanie file in your account. It is possible to do this? When trying to remove, if no such file exists, the error falls, which I so need a check.

**Comment by kunalvarma05** [comment]
This should work:
```php
/**
 * Get file if it exists else return false
 *
 * @param  string $path    Path to file
 * @param  \Kunnu\Dropbox\Dropbox $dropbox Dropbox
 *
 * @return \Kunnu\Dropbox\Models\FileMetadata | boolean
 */
function getFileIfExists($path, $dropbox)
{
    try {
        return $dropbox->getMetadata($path);
    } catch (DropboxClientException $e) {
        // File does not exist
        // Log error
    }

    return false;

}

$dropbox = new Dropbox($app, $config);
$file = getFileIfExists('/doesnotexist.jpg', $dropbox);

if ($file) {
    // File exists, delete the file
} else {
    // File does not exist
}
```

**Comment by reimax** [comment]
not work:

`{"error_summary": "path/not_found/", "error": {".tag": "path", "path": {".tag": "not_found"}}}`

and error

`//Something went wrong
        if ($rawResponse->getStatusCode() >= 400) {
            throw new DropboxClientException($rawResponse->getBody());
        }`
