### ISSUE TITLE
Failed when installing API

### ISSUE THREAD

**Issue by matheusmaximo** [kunalvarma05/dropbox-php-sdk#28]
Hello,

I'm trying to install the API, but got an error and not conclude it:

**$ composer require kunalvarma05/dropbox-php-sdk
Using version ^0.1.5 for kunalvarma05/dropbox-php-sdk
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)**
  - Installing kunalvarma05/dropbox-php-sdk (v0.1.5)
    Loading from cache

**Writing lock file
Generating autoload files**
> Illuminate\Foundation\ComposerScripts::postUpdate
> php artisan optimize

  [BadMethodCallException]
**  Method accessible does not exist.

Script php artisan optimize handling the post-update-cmd event returned with error code 1

Installation failed, reverting ./composer.json to its original content.**

After this, my composer broke and I should restore everything to can work again.

Can you help me? What's wrong?

**Comment by kunalvarma05** [comment]
@matheusmaximo Can you share some more info/output regarding the error you got? 

However, I'll test it with Laravel.

**Comment by kunalvarma05** [comment]
@matheusmaximo The installer seems to be working fine. I tried it on a fresh installation of laravel 5.3. Works smoothly. 

```
$ composer require kunalvarma05/dropbox-php-sdk
Using version ^0.1.5 for kunalvarma05/dropbox-php-sdk
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
    Finished: success: 0, skipped: 0, failure: 3, total: 3
  - Installing guzzlehttp/promises (v1.3.1)
    Downloading: 100%

  - Installing psr/http-message (1.0.1)
    Loading from cache

  - Installing guzzlehttp/psr7 (1.3.1)
    Loading from cache

  - Installing guzzlehttp/guzzle (6.2.2)
    Downloading: 100%

  - Installing kunalvarma05/dropbox-php-sdk (v0.1.5)
    Downloading: 100%

Writing lock file
Generating autoload files
> Illuminate\Foundation\ComposerScripts::postUpdate
> php artisan optimize
Generating optimized class loader
The compiled class file has been removed.
```

Doesn't seems to be a problem with the package. 

However, can you clear the composer cache and give it a try?

Thanks.

**Comment by Austinb** [comment]
@matheusmaximo I had the same issue on Laravel 4.2 so I assume you are using an older version of laravel.  I had to work my way around the tightenco/collect library using a zip install because that required library was the problem.  The tightenco/collect ends up overloading part of the Illuminate core which then breaks a lot of stuff due to changes in later versions of the core framework .  It appears it should be fine in  Laravel > 5.2 but I have not tested it until we migrate off of 4.2 and slowly work that direction.
