### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by david63** [kunalvarma05/dropbox-php-sdk#3]
Will there be any error/exception handling added?

**Comment by kunalvarma05** [comment]
Yep, working on it. For now, a [DropboxClientException](../blob/master/src/Dropbox/Exceptions/DropboxClientException.php) would be thrown. 

```php
use Kunnu\Dropbox\Exceptions\DropboxClientException;

try {
    $file = $dropbox->getMetadata("/file-not-exists.txt");
} catch (DropboxClientException $e) {
    //
}
```
