### ISSUE TITLE
AccessToken.php incomplete

### ISSUE THREAD

**Issue by Austinb** [kunalvarma05/dropbox-php-sdk#31]
When I run a $dropbox->getAuthHelper()->getAccessToken() parts of the properties are missing from this class:
```php
Kunnu\Dropbox\Models\AccessToken Object
(
    [token:protected] => nmgs5Bp7E84AAAAAAAABGLCZGfVNYJ1MRNMivK-bsjS9KAhFKnnEcGaJsFTsNJgi
    [tokenType:protected] => 
    [bearer:protected] => 
    [uid:protected] => 2199999999
    [accountId:protected] => 
    [teamId:protected] => 
    [data:protected] => Array
        (
            [access_token] => nmgs5Bp7E84AAAAAAAABGLCZGfVNYJ1MRNMivK-bsjS9KAhFKnnEcGaJsFTsNJgi
            [token_type] => bearer
            [uid] => 2199999999
            [account_id] => dbid:AAANpK8MVW8cpkGooeYBPnWw-...
        )
)
```

According to https://www.dropbox.com/developers-v1/core/docs#oa2-token the response is 
```json
{"access_token": "ABCDEFG", "token_type": "bearer", "account_id": "dbid:AAH4f99T0taONIb-OurWxbNQ6ywGRopQngc", "uid": "12345"}
```
but the __construct is looking for properties like tokenType instead of token_type and accountId instead of account_id. Good news is you can use magic method to grab what I need that is missing from the defined functions.  

The only other thing I could think of is maybe I am using the wrong version of the Dropbox api?  I click on the v2 api but the authorize takes me to developers-v1 path and there is no page for v2.

**Comment by kunalvarma05** [comment]
Thanks for the heads up @Austinb!
