### ISSUE TITLE
PHP giving error

### ISSUE THREAD

**Issue by david63** [kunalvarma05/dropbox-php-sdk#34]
I am getting the following error with PHP 7.0.13 but not with PHP 7.0.8

Error in call to API function "files/upload_session/finish": HTTP header "Dropbox-API-Arg": cursor.offset: expected integer, got float

**Comment by jmrieger** [comment]
If you're making a call directly to uploadChunked and specifying a chunk size, make sure that the chunk size is cast as an integer:

`$chunkSize = intval( $chunkSize );`

If you're using the regular upload() function, I think the following line should be changed:
https://github.com/kunalvarma05/dropbox-php-sdk/blob/f39cf3bdd7d7ed75c678504646a01a79d95e729d/src/Dropbox/Dropbox.php#L981

`$chunkSize = intval($fileSize / 2);`

**Comment by kunalvarma05** [comment]
@jmrieger Thanks for pointing out! 

Send in a PR if possible and I'll merge it right away.

**Comment by david63** [comment]
I can confirm that the fix by jmrieger resolves this issue

**Comment by kunalvarma05** [comment]
Thanks @jmrieger and @david63!
