### ISSUE TITLE
How to get "Access Token" without redirection authentication

### ISSUE THREAD

**Issue by dev4press** [kunalvarma05/dropbox-php-sdk#37]
I have created to code to get users to authorize application, by getting the confirmation code, and not using redirection URL:

`use Kunnu\Dropbox\Dropbox;
use Kunnu\Dropbox\DropboxApp;

$app = new DropboxApp('app_key', 'app_secret');

$box = new Dropbox($app);
$ath = $box->getAuthHelper();
$url = $ath->getAuthUrl();`

When the user visits the URL and approves the app, he will get the code looking like this:
-BgHSLYOHdkABBCCAAAIxngqv6sfnaebCIFkD-mRc92

Now, when I try to get AccessToken, I tried to use $ath->getAccessToken() method, but this method requires 2 parameters: first one is the code (I assume the code user got after the approval), and second one is the 'state' array. But, since I have not used the redirection authentication method, I don't have the 'state' array values.

How can I get AccessToken when I use this method to authenticate the app? Old API had method to this with path '1/oauth2/token'.

Milan

**Comment by kunalvarma05** [comment]
@dev4press This has been fixed. The CSRF/State validation won't be handled implicitly if a `redirect_uri` is not provided. 

Simply pass the `code` that you obtain as the only parameter to the [`getAccessToken`](../blob/master/src/Dropbox/Authentication/DropboxAuthHelper.php#L203) method;

```php
$code = 'BgHSLYOHdkABBCCAAAIxngqv6sfnaebCIFkD-mRc92';
$authHelper->getAccessToken($code);

```

Thanks for the heads up!
