### ISSUE TITLE
Can't find the GuzzleHttp library 

### ISSUE THREAD

**Issue by adialexpop** [kunalvarma05/dropbox-php-sdk#39]
Hello,

I cannot create an instance for the Dropbox class, I think the main reason is because I don't have the Guzzle and Psr libraries. Where can I find this library and which version should I use ?

![image](https://cloud.githubusercontent.com/assets/17698055/23067933/15f7a392-f52a-11e6-9943-e3d702942ed8.png)

Thanks!

**Comment by kunalvarma05** [comment]
@adialexpop You need to install this package through [Composer](https://getcomposer.org/). [Guzzle](http://docs.guzzlephp.org/en/latest/) will be installed along with it.
