### ISSUE TITLE
Connot require itself

### ISSUE THREAD

**Issue by code-sallo** [kunalvarma05/dropbox-php-sdk#40]
Hey, it's my first time with the composer.

I downloaded the ZIP and extracted it into my project. In the directory "dropbox-php-sdk-master" I run the composer, but it doesn't work :(

`sst@ronda:~/public_html/wukos_dbx/inc/dropbox-php-sdk-master$ composer require kunalvarma05/dropbox-php-sdk

Using version ^0.1.5 for kunalvarma05/dropbox-php-sdk
./composer.json has been updated
Root package 'kunalvarma05/dropbox-php-sdk' cannot require itself in its composer.json
Did you accidentally name your root package after an external package?`

Can anybody help me with this problem? Thanks!

**Comment by kunalvarma05** [comment]
@code-sallo No worries. Here's a neat guide to [Get started with Composer](https://scotch.io/tutorials/a-beginners-guide-to-composer).  

Once you're thorough with how Composer works and why it is used (for dependency management), the following will be quite apparent:

1. Go inside your project's root (`~/my-project`)
2. Run `composer init` (https://getcomposer.org/doc/03-cli.md#init)
3. Then run `composer require kunalvarma05/dropbox-php-sdk` (https://getcomposer.org/doc/03-cli.md#require)
4. 👆 This will install the `kunalvarma05/dropbox-php-sdk` package and all it's dependencies in the `vendor/` directory inside your project's root.
5. Then, require the `vendor/autoload.php` file in your project's file and start working with the API. (https://github.com/kunalvarma05/dropbox-php-sdk/wiki/Configuration)

Cheers :)

**Comment by hut3y** [comment]
just need change to another direction
i mean movedown to another one and try again
