### ISSUE TITLE
Any way to get the icon of an uploaded file?

### ISSUE THREAD

**Issue by alimovz** [kunalvarma05/dropbox-php-sdk#42]
The old Dropbox php sdk returns, among other things, the "icon" and "mime_type" of any uploaded file. Any way I can get that through:

```
$result = $dropbox->upload("thumb.png", "/path/to/file/thumb.png", ['autorename' => true]);
print_r($result);
```

**Comment by kunalvarma05** [comment]
As per Dropbox's current [Documentation](https://www.dropbox.com/developers/documentation/http/documentation), there seems to be no way to obtain the `icon` or `mime_type` info for a file. Perhaps, you'll have to do it on your own by extracting the extension of the file from it's path and then figuring out the file type based on the extension.
