### ISSUE TITLE
Fatal error when searching in not existing folder

### ISSUE THREAD

**Issue by tilekus** [kunalvarma05/dropbox-php-sdk#43]
This error comes when i'm trying to find file in non existing folder, or if dropbox won't be able find at least one file/folder

[04-Mar-2017 01:12:15 UTC] PHP Fatal error:  Uncaught exception 'Kunnu\Dropbox\Exceptions\DropboxClientException' with message '{"error_summary": "path/not_found/.", "error": {".tag": "path", "path": {".tag": "not_found"}}}' in /path_to_folder/dropbox/kunalvarma05/dropbox-php-sdk/src/Dropbox/Http/Clients/DropboxGuzzleHttpClient.php:67
Stack trace:
/path_to_folder/dropbox/kunalvarma05/dropbox-php-sdk/src/Dropbox/DropboxClient.php(155): Kunnu\Dropbox\Http\Clients\DropboxGuzzleHttpClient->send('https://api.dro...', 'POST', '{"path":"\\/2017...', Array)
/path_to_folder/dropbox/kunalvarma05/dropbox-php-sdk/src/Dropbox/Dropbox.php(250): Kunnu\Dropbox\DropboxClient->sendRequest(Object(Kunnu\Dropbox\DropboxRequest))
/path_to_folder/dropbox/kunalvarma05/dropbox-php-sdk/src/Dropbox/Dropbox.php(264): Kunnu\Dropbox\Dropbox->sendRequest('POST', '/files/list_fol...', 'api', Array, NULL)
/ho in /path_to_folder/dropbox/kunalvarma05/dropbox-php-sdk/src/Dropbox/Http/Clients/DropboxGuzzleHttpClient.php on line 67

**Comment by tilekus** [comment]
This issue only appears if folder is not exist in DropBox which is sending as first parameter
$dropbox->search('/not_exist_folder/', 'file_name')
request as below return fatal error

**Comment by kunalvarma05** [comment]
@tilekus That's an expected Exception. If you try searching inside a non-existing folder, Dropbox's API will respond with an error.

More Info => https://www.dropbox.com/developers/documentation/http/documentation#SearchError

**Comment by markfb** [comment]
Firstly, many thanks for pulling this great SDK together, I was starting to panic when the native Dropbox API was deprecated... I'm seeing the same exception using listFolder when the folder doesn't exist:

$listFolderContents = $dropbox->listFolder($path);

Is this also by design as it didn't throw an exception in the native V1 API? I'm struggling to find an elegant way around it....

**Comment by kunalvarma05** [comment]
@markfb Dropbox's API only returns errors (in responses). See => https://www.dropbox.com/developers/documentation/http/documentation#error-handling

Here's how to handle the exceptions thrown by the SDK:

```php
try {
    $listFolderContents = $dropbox->listFolder($path);
} catch (DropboxClientException $e) {
    echo $e->getMessage();
}
```

Cheers!

**Comment by markfb** [comment]
I've now found a way around this. Thanks!

**Comment by toddalbert** [comment]
@markfb What was your solution?

**Comment by markfb** [comment]
Unfortunately it isn't particularly elegant. I'm storing a document count for each folder in my database and checking that it's 1 or more before using listFolder...
