### ISSUE TITLE
Delete file, folder permanently

### ISSUE THREAD

**Issue by lindevs** [kunalvarma05/dropbox-php-sdk#44]
Hi, it is posible using this library delete file, folder permanently?
[https://www.dropbox.com/developers-v1/core/docs#fileops-permanently-delete](https://www.dropbox.com/developers-v1/core/docs#fileops-permanently-delete)

**Comment by kunalvarma05** [comment]
According to the [Dropbox's docs](https://www.dropbox.com/developers/documentation/http/documentation#files-permanently_delete): "This endpoint is only available for Dropbox Business apps.".

I haven't yet implemented this endpoint yet. However, for now you can do it like this:

```php
$dropbox->postToAPI('/files/permanently_delete', ['path' => "/path-to-file.txt"]);
```

Thanks.
