### ISSUE TITLE
Installing via composer does not autoload classes

### ISSUE THREAD

**Issue by tomdtn** [kunalvarma05/dropbox-php-sdk#47]
The class files are unaccessible even after they've been installed via composer.

````
use Kunnu\Dropbox\DropboxApp;
````

Throws an error and the class is not found. My autoload file has been included properly and other vendor dependencies are picked up without problem.

**Comment by kunalvarma05** [comment]
I'm unable to reproduce this issue.

Can you send me a screenshot or dump of the error exception you're getting?

**Comment by tomdtn** [comment]
I can't send you application code since it's my company's project.

For reference, we're using Symfony and moving from the v1 dropbox sdk to this. I wasn't able to get to an exception because my class files were never loaded (I can see in my IDE when the class files are loaded). Trying to integrate your code (the use statement), yielded no results, even after installing via composer...

Closing this as we are going to go with the Javascript SDK. Left the details in case someone else comes across the same problem.

**Comment by kunalvarma05** [comment]
Your IDE not loading (autocomplete) them and PHP throwing an error at runtime are two different issues.

**Comment by tomdtn** [comment]
So, I'm supposed to just insert this into a raw text editor? I find it hard to believe that somehow, just for your project only, needs to be loaded differently via composer and autoload.

If I were to load this and test it, it would just say Class not Found. 

In order to show you what I'm saying is correct, I'll go ahead and load it into our service then post a screenshot.

**Comment by tomdtn** [comment]
Normally, this causes a Class not Found error. Somehow, the import is working even though my IDE says it's not (loaded a test case into an environment and it didn't throw an exception). Most likely, this is some conflict/resolution of the namespace.
