### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by em67re** [kunalvarma05/dropbox-php-sdk#48]
Is it possible to use without Hi Composer?

**Comment by kunalvarma05** [comment]
Yes. 

Download the files of the package from [the releases page](https://github.com/kunalvarma05/dropbox-php-sdk/releases). Then download the files of all the dependencies (listed in the `require` block of the composer.json file) of the package and `require` or `autoload` them in your application.

However, I'd strongly recommend against this, especially if you're using it in production.
