### ISSUE TITLE
Class DropboxFile not found

### ISSUE THREAD

**Issue by briandelacruz** [kunalvarma05/dropbox-php-sdk#49]
Currently migrating API v1 to v2, and I'm having a hard time on uploading a file and receiving an error.

Error:
127.0.0.1:39086 [500]: /dropbox-php-sdk/upload.php - Class 'Kunnu\Dropbox\DropboxFile' not found in /var/www/html/dropbox-php-sdk/upload.php on line 18
***********************************************************************************************************************
This is my source code.

<!DOCTYPE html>
<html>
<body>

<form action="" method="post" enctype="multipart/form-data">
    Select image to upload:
    <input type="file" name="fileToUpload" id="fileToUpload">
    <input type="submit" value="Upload Image" name="submit">
</form>

</body>
</html>

<?php 

use Kunnu\Dropbox\DropboxFile;

$dropboxFile = new DropboxFile(__DIR__ . '$_FILES["fileToUpload"]["name"]');

$file = $dropbox->upload($dropboxFile, '$_FILES["fileToUpload"]["name"]', ['autorename' => true]);

//Uploaded File
$file->getName();

**Comment by kunalvarma05** [comment]
Are you using the package through Composer? If so, you need to require the `vendor/autoload.php` file before you use any class in the package. 

If you're not using Composer, you need to manually include all the files from the package, first.

**Comment by briandelacruz** [comment]
Thank you! You helped us a lot! :D

**Comment by khanrashid08** [comment]
Dear kunalvarma05, I am working on cakephp 2.6.1 and i want to integrate dropbox API. After generating file via composer in APP/Vendor dir, I am calling controller class file 
use Kunnu\Dropbox\DropboxApp;
use Kunnu\Dropbox\Dropbox;
but found error: "( ! ) Fatal error: Class 'Kunnu\Dropbox\DropboxApp' not found in /var/www/html/ecotrak/app/Controller/DropboxController.php on line 37"

Note: After running composer, "vendor" directory created in App/Vendor > vendor
Please help me resolve issue.

**Comment by siddharth-prajapati** [comment]
did you use this **App::uses()** to load vendor files
