### ISSUE TITLE
Logging in with App Key/Secret

### ISSUE THREAD

**Issue by andrewgoodnz** [kunalvarma05/dropbox-php-sdk#50]
Hi, 

Is it possible to allow an app to login rather than a user? Refer to https://www.dropbox.com/developers/reference/auth-types#app Under "App Authentication" 

> App Authentication
> 
> This type only uses the app's own app key and secret, and doesn't identify a specific user or team. The app key and secret are transmitted in place of a username and password using "HTTP basic access authentication".

**Comment by kunalvarma05** [comment]
As of now, it's not possible to do so. I don't recall App Authentication being documented while I was working on the Auth part. 

However, I'll look into it. Would appreciate any help or contribution.

Cheers!

**Comment by RanaAshish** [comment]
@kunalvarma05 Any update on this? Can we do App Authentication now?
