### ISSUE TITLE
Fatal error: Class 'Kunnu\Dropbox\DropboxApp' not found 

### ISSUE THREAD

**Issue by Vshri** [kunalvarma05/dropbox-php-sdk#52]
Fatal error: Class 'Kunnu\Dropbox\DropboxApp' not found 

I am facing this issue while creating instance of DropboxApp. Below is my code:

use Kunnu\Dropbox\Dropbox;
use Kunnu\Dropbox\DropboxApp;

$dropboxKey='xxxx';
$dropboxSecret='xxx';
$accessToken='xxxxxx'; 
$appName='TestAppDrpbx/1.0';
$callbackUrl='http://localhost:8081/TestDBApp/dropbox_finish.php';

$app = new DropboxApp($dropboxKey,$dropboxSecret,$accessToken);

$dropbox = new Dropbox($app);

Thanks!!

**Comment by kunalvarma05** [comment]
1. Are you using [Composer](https://getcomposer.org/)? 
2. If yes, have you included the **autoload.php** file? 

```php
require __DIR__ . '/vendor/autoload.php';

use Kunnu\Dropbox\Dropbox;
use Kunnu\Dropbox\DropboxApp;

$dropboxKey='xxxx';
$dropboxSecret='xxx';
$accessToken='xxxxxx';
$appName='TestAppDrpbx/1.0';
$callbackUrl='http://localhost:8081/TestDBApp/dropbox_finish.php';

$app = new DropboxApp($dropboxKey,$dropboxSecret,$accessToken);

$dropbox = new Dropbox($app);
```

Make sure the **autoload.php** file is included.

**Comment by Vshri** [comment]
But i cannot find autoload.php file in library

**Comment by kunalvarma05** [comment]
You're probably new to Composer. Follow the steps in **[this comment](https://github.com/kunalvarma05/dropbox-php-sdk/issues/40#issuecomment-280913244)**.

**Comment by Vshri** [comment]
Thank you so much

**Comment by divyaacrazy** [comment]
I am also facing the same issue. I have included the 'vendor/autoload.php'  by using composer. Is anything else need to be done to clear the error.

Thank You!




Fatal error: Class 'Kunnu\Dropbox\DropboxApp' not found 

**My Code:**
require __DIR__ . '/vendor/autoload.php';

use Kunnu\Dropbox\Dropbox;
use Kunnu\Dropbox\DropboxApp;

$dropbox_client_id='**';
$dropbox_client_secret='**';
$dropbox_access_token='**';


//Configure Dropbox Application
$app = new DropboxApp($dropbox_client_id, $dropbox_client_secret, $dropbox_access_token);

//Configure Dropbox service
$dropbox = new Dropbox($app);

//Get File Metadata
$fileMetadata = $dropbox->getMetadata("/helloworld.txt");

//File Name
$fileMetadata->getName();

**Comment by jmmaguigad** [comment]
@divyaacrazy it should be require __DIR__ . '/vendor/autoload.php'; not require DIR . '/vendor/autoload.php';
