### ISSUE TITLE
dropbox_authorization will this deprecate?

### ISSUE THREAD

**Issue by briandelacruz** [kunalvarma05/dropbox-php-sdk#53]
Whenever we get to authorization page(page w/allow button) and we pressed allow it will go to the specified redirect uri, if you inspect element the page you will see on the network tab -> header tab there is an authorization_submit where the URL is https://www.dropbox.com/1/oauth/authorize_submit. Is this okay? are there will be any problem for deprecation of Dropbox api?
![screenshot from 2017-05-26 13-43-24](https://cloud.githubusercontent.com/assets/17946515/26768364/e53dd0b4-49d9-11e7-881d-6c57b1a4f110.png)

**Comment by kunalvarma05** [comment]
This doesn't seem to be a problem related to the SDK/package. It's internal to Dropbox.

**Comment by briandelacruz** [comment]
Thank you sir on replying with this issue. :) Have a good day. Tomorrow's
the day on deprecating the Dropbox version 1.
Kudos! :D

**Comment by briandelacruz** [comment]
Good Morning,

Is the Upload file by URL where
$asyncJobID = $dropbox->saveUrl("/my-logo.png", '
http://mywebsite.com/wp-content/uploads/2016/06/logo.png');
have limit? I mean can we upload like chunked files using this method?

**Comment by kunalvarma05** [comment]
Hey @briandelacruz, can you open a new issue for this? Just in case someone else has the same question, it'll be easier to find it.

**Comment by briandelacruz** [comment]
Good Morning,

I did, and my colleague answered your question on the issue that I made.

kind regards,
