### ISSUE TITLE
Error on exception

### ISSUE THREAD

**Issue by matthieubrunet** [kunalvarma05/dropbox-php-sdk#54]
Hi
To validate my access Token, i put getAccessToken into a try...catch. But I get this error :
`A PHP Error was encountered
Severity: 4096
Message:  Object of class Kunnu\Dropbox\Models\AccessToken could not be converted to string
Filename: database/DB_driver.php
Line Number: 952`

Here is my code :

```
$token = $this->input->post("token"); // aka code-presented-directly-to-the-user
		
//Configure Dropbox Application
$app = new Kunnu\Dropbox\DropboxApp($this->config->item("dropbox_key"), $this->config->item("dropbox_secret"));
		
//Configure Dropbox service
$dropbox = new Kunnu\Dropbox\Dropbox($app);
		
//DropboxAuthHelper
$authHelper = $dropbox->getAuthHelper();
try
{
	$accessToken = $authHelper->getAccessToken($token);
}
catch(Exception $e)
{
	die(json_encode(array("status"=>"error", "error"=>"Access token invalide ($token) : " . $e->getMessage())));
}
```

It only happen for a certain error type, which is displayed when I don't use try...catch :

```
An uncaught Exception was encountered
Type: Kunnu\Dropbox\Exceptions\DropboxClientException
Message: {"error_description": "code has already been used", "error": "invalid_grant"}
Filename: /Applications/MAMP/htdocs/crm/application/vendor/kunalvarma05/dropbox-php-sdk/src/Dropbox/Http/Clients/DropboxGuzzleHttpClient.php
Line Number: 67
```
I know how to fix the error. I just want to catch it.

Other error types are correctly caught without throwing this php error.

Thanks

**Comment by kunalvarma05** [comment]
The [`getAccessToken`](https://kunalvarma05.github.io/dropbox-php-sdk/master/Kunnu/Dropbox/Authentication/DropboxAuthHelper.html#method_getAccessToken) method returns the [`AccessToken`](https://kunalvarma05.github.io/dropbox-php-sdk/master/Kunnu/Dropbox/Models/AccessToken.html) class's object and not a string, which is being stored in the `$accessToken` variable. To fetch the access token (as a string) from the AccessToken class's object, call the [`getToken`](https://kunalvarma05.github.io/dropbox-php-sdk/master/Kunnu/Dropbox/Models/AccessToken.html#method_getToken) method.
