### ISSUE TITLE
Fatal error: Uncaught exception

### ISSUE THREAD

**Issue by rafal-leap** [kunalvarma05/dropbox-php-sdk#55]
`Fatal error: Uncaught exception 'Kunnu\Dropbox\Exceptions\DropboxClientException' with message '{"error_summary": "path/conflict/file/..", "error": {".tag": "path", "path": {".tag": "conflict", "conflict": {".tag": "file"}}}}' in /includes/dropbox_v2/includes/vendor/kunalvarma05/dropbox-php-sdk/src/Dropbox/Http/Clients/DropboxGuzzleHttpClient.php:67 Stack trace: #0 /includes/dropbox_v2/includes/vendor/kunalvarma05/dropbox-php-sdk/src/Dropbox/DropboxClient.php(161): Kunnu\Dropbox\Http\Clients\DropboxGuzzleHttpClient->sendchttps://content...', 'POST', VDAIx1E1xAIxACIxB4-4-j_...', Array, Array) #1 includes/dropbox_v2/includes/vendor/kunalvarma05/dropbox-php-sdk/src/Dropbox/Dropbox.php(254): Kunnu\Dropbox\DropboxClient->sendRequest(Object(Kunnu\Dropbox\DropboxRequest), NULL) #2 includes/dropbox_v2/includes/vendor/kunalvarma05/dropbox-php-sd in includes/dropbox_v2/includes/vendor/kunalvarma05/dropbox-php-sdk/src/Dropbox/Http/Clients/DropboxGuzzleHttpClient.php on line 67 `

Randomly I'm getting this error while uploading the file to dropbox. I'm not very clear where to start?

**Comment by kunalvarma05** [comment]
This is due to a conflict in the file name/path. A file with a similar name already exists on the upload path.

If you want to overwrite the old file, pass the `mode` as `overwrite `.

```php
$uploadedFile = $dropbox->upload($pathToFile, "/my-file.txt", ['mode' => 'overwrite']);
```

[Dropbox File Upload](https://www.dropbox.com/developers/documentation/http/documentation#files-upload)
