### ISSUE TITLE
Wrong Requirements

### ISSUE THREAD

**Issue by danielschweiger** [kunalvarma05/dropbox-php-sdk#56]
As system requirements say in "Getting startet" = PHP > 5.5.0

But "tightenco/collect": "^5.2" needs:
"php": ">=5.6.4"

**Comment by kunalvarma05** [comment]
[Fixed](https://github.com/kunalvarma05/dropbox-php-sdk/wiki/Getting-Started/4511af20ae5bd9fcbe39bf95a7aa6f487974cf81). Thanks.
