### ISSUE TITLE
Problem with authorizoation

### ISSUE THREAD

**Issue by tommek111** [kunalvarma05/dropbox-php-sdk#57]
I can get an access token for a client of my application, but when I try to list a folder content with $dropbox->listFolder("/") I get an error:
Error in call to API function "files/list_folder": Invalid authorization value in HTTP header "Authorization": "Bearer". Expecting "Bearer ".

Any idea what I'm doing wrong?

**Comment by kunalvarma05** [comment]
Did you set the Access Token before using the listFolder endpoint? Can you share the code?

**Comment by tommek111** [comment]
Sorry, my mistake. I was using the old instance of Dropbox class after authentication, but when I set Access Token everything works ok.
Thank you.
