### ISSUE TITLE
Large file conflict in Upload File URL

### ISSUE THREAD

**Issue by briandelacruz** [kunalvarma05/dropbox-php-sdk#58]
Hello Mr. Kunal Varma,

The API is working properly but I tried to upload a 68+mb file using Upload file URL, and nothing happens. I can only upload files with a size of maybe 5mb and below.

Is the Upload file by URL where 
$asyncJobID = $dropbox->saveUrl("/my-logo.png", 'http://mywebsite.com/wp-content/uploads/2016/06/logo.png');
have file size limit? I mean can we upload like chunked files using this method?

kind regards,

**Comment by kunalvarma05** [comment]
Are you using the [`checkJobStatus()`](../blob/master/src/Dropbox/Dropbox.php#L738) method, which gives more information on the job?

See [**Upload File By URL (Check Job Status)**](https://github.com/kunalvarma05/dropbox-php-sdk/wiki/Upload-and-Download-Files#check-job-status)

**Comment by tristanlesaca0** [comment]
checkJobStatus() returns in_progress but the file is not uploaded to my Dropbox

**Comment by kunalvarma05** [comment]
@briandelacruz @tristanlesaca0 Is it still not getting uploaded to your Dropbox? I'm unable to reproduce this issue. I tried a 300mb+ file and it was uploaded within seconds (after calling the `saveUrl()` method). This does not seem to be an issue with the package/SDK.

**Comment by kanu786** [comment]
@kunalvarma05  I am uploading large file size image its not uploading .. Whenver i tried with small size its getting uploaded to dropbox
My code is below:-


                         $file = $_FILES['file'];
			    // File Path
			    $fileName = $file['name'];
			    $filePath = $file['tmp_name'];

			    try {
			        // Create Dropbox File from Path
			        $dropboxFile = new DropboxFile($filePath);

			        // Upload the file to Dropbox
			        //$dropbox->createFolder("/My Folder");
			        $uploadedFile = $dropbox->upload($dropboxFile, "/" . $fileName, ['autorename' => true]);

			        // File Uploaded
			        echo $uploadedFile->getPathDisplay();
			    } catch (DropboxClientException $e) {
			        echo $e->getMessage();
			    }

I am alos using Chunked File Upload but that is alos not working. Can you help me
