### ISSUE TITLE
How would you upload and overwrite a file without renaming it

### ISSUE THREAD

**Issue by kenma9123** [kunalvarma05/dropbox-php-sdk#59]
I'm trying to upload a file with the same name for example `file.png` and I have the same file name on dropbox folder. When I use `upload` method it does rename the file to avoid conflict. When I set param option `['autorename' => false]` it doesn't work and give me errors instead.

I would like to upload the same file and stays it as a revision for example. What would be the right approach to do this? Thanks in advance.

**Comment by kunalvarma05** [comment]
This is can be done by explicitly passing an `update` type to the `mode` param. The Dropbox documentation has it. **See: https://www.dropbox.com/developers/documentation/http/documentation#files-upload**

```php
// Fetch the File Metadata
$file = $dropbox->getMetadata("MY-AWESOME-FILE");
// Get the file's revision hash
$revision = $file->getRev();

$params = [
        'mode' => [
            ".tag" => "update",
            'update' => "79304b4a4c9"
        ],
        'autorename' => false
    ];

$updatedFile = $dropbox->upload("path/to/MY-AWESOME-FILE", "/MY-AWESOME-FILE", $params);

```

Let me know if it doesn't work.
