### ISSUE TITLE
Request Response

### ISSUE THREAD

**Issue by taheruddin** [kunalvarma05/dropbox-php-sdk#60]
Hi,

I am trying to use the DropboxResponse and DropboxRequest. But no example or documentation. 

`$req = new DropboxRequest('POST', 'list_folder', $user['dpx_token'] );
			$resp = new DropboxResponse($req);
			echo "<pre>"; var_dump($resp->getBody()); echo "</pre>";`

I tried this code but it is giving NULL. I want to get a list of folders and files (https://dropbox.github.io/dropbox-api-v2-explorer/#files_list_folder).

**Comment by taheruddin** [comment]
`$resp = $dropbox->sendRequest("POST", 'list_folder', 'api', ['path' => ""]);
			echo "<pre>"; var_dump($resp->getBody()); echo "</pre>";`

I have tried this code also but not working. Giving error - Error (4xx)</h1> We can't find the page you're looking for. ...

**Comment by kunalvarma05** [comment]
The endpoint you've entered is incorrect. Its not `/list_folder`, its `/files/list_folder`. However, the SDK already has a method that covers the `/files/list_folder` endpoint. 

It's [documented in the Wiki](https://github.com/kunalvarma05/dropbox-php-sdk/wiki/Working-with-files#list-folder-contents). Here's the API: [**`listFolder()`**](https://kunalvarma05.github.io/dropbox-php-sdk/master/Kunnu/Dropbox/Dropbox.html#method_listFolder)

**Comment by taheruddin** [comment]
It worked. Thanks
