### ISSUE TITLE
Does this work in 3.2.1?

### ISSUE THREAD

**Issue by Hartenheer** [kunalvarma05/dropbox-php-sdk#61]
I've installed everything and filled it in.
There is an apps folder created by the extension,
But nothing else happens.
What is the frequency of backup?

I also use the extension Auto database backup (3.2).
Could that be the problem?

Sorry for my bad English, Google uses

**Comment by david63** [comment]
You have posted this in the wrong place - this is the for the dropbox sdk, not the applications that use it.

But in answer to your question - yes.

**Comment by Hartenheer** [comment]
I use Dropbox upload for autobackup and Auto database backup (3.2)

Dropbox upload for autobackup does not work with me

Auto database backup (3.2) turn off?

**Comment by david63** [comment]
This is not the place for this discussion - please use phpbb.com
