### ISSUE TITLE
Call to undefined function DropboxApp()

### ISSUE THREAD

**Issue by skerit** [kunalvarma05/dropbox-php-sdk#62]
In my Yii 1 application I installed the package:

```
composer require kunalvarma05/dropbox-php-sdk
```

The `autoload.php` files have been updated and are required, but I still get the error:

```
Call to undefined function DropboxApp()
```

This must have something to do with the `kunalvarma05` part in `kunalvarma05/dropbox-php-sdk` not matching the namespace used in the php files.

I have a few other external packages that work fine, but the namespace and directory name actually match of those packages.

**Comment by marcus-at-localhorst** [comment]
Stupid question: You call it like this: `$app = new DropboxApp(...);`? Because I just had the same error and forgot the `new` Keyword.

**Comment by skerit** [comment]
@marcus-at-localhorst Well this is embarrassing... that was indeed it!
