### ISSUE TITLE
Uploaded files get corrupted 

### ISSUE THREAD

**Issue by ogwugo** [kunalvarma05/dropbox-php-sdk#63]
I am new to using this API, I have implemented downloading file and it works great, but when I upload the file get corrupted, only image files works. pdf gets corrupted, video will cut at around 30percent and stop playing.  can some one help, the file sizes are from 0.5 - 200mb atimes... here is my script:

             // dropbox uploads
             use Kunnu\Dropbox\DropboxFile;
             $file = ($_FILES["material_file"]["tmp_name"]);

        $name = ($_FILES["material_file"]["name"]);
       // $ext = (explode(".", $name)); # extra () to prevent notice
       // $ext = end($ext);
       $name = $app->UploadPathBuilder($name);
    //$name = str_replace(' ','_',$name);
            $dropboxFile = new DropboxFile($file);
            $file = $dropbox->upload($dropboxFile, "/".$upload_folder."/".'_' . ($name), ['autorename' => true]);
            $temporaryLink = $dropbox->getTemporaryLink($file->getPathLower());
            //Get File Metadata

**Comment by kunalvarma05** [comment]
I was able to upload a `~300 MB` video file and a `~14 MB` PDF file. Both were successfully uploaded without being corrupted or cut off.

Could you validate that the files you're uploading are not corrupted or cut off before uploading them to through the SDK?

**Comment by ogwugo** [comment]
I have discovered the issue, it should be a server issue, I used another
server and it worked fine!
