### ISSUE TITLE
Calling listFolderContinue to get changes in subfolders returns empty [entries]

### ISSUE THREAD

**Issue by nofont** [kunalvarma05/dropbox-php-sdk#64]
Hi!

Adding, deleting or chaging a file or folder in my root folder and then calling listFolderContinue($dbxCursor); works perfectly.

But if I do the same in a sub-folder the [entries]-array in the repsponse is always empty.

Example:
I add the file "test.txt" and the folder "test_images" in /tests/ and then calls `$changes = $dbxClient->listFolderContinue($dbxCursor);` where the cursor is a stored cursor from my precious call.

Response:

```
Kunnu\Dropbox\Models\MetadataCollection Object
(
    [data:protected] => Array
        (
            [entries] => Array
                (
                )
            [cursor] => AAFsvB_59VQxsr2KAkQuK3BJw4HjBRok-FBcABhjF0tORjRrvddSEgPraNmFm3Tu7zos85OJ3zRfWJIN0IMUOt8NwVwAdL39j5rQvR7P3iGeRvIUsW22fi0_eV1VH73J6Sd_qOrGqeWtJfAXiPYftvjJ
            [has_more] => 
        )
)

```
Anyone else have hade this issue?

**Comment by nofont** [comment]
This was an issue due to my own code, not the SDK.

**Comment by fernaog** [comment]
Hi nofont,

What was your code issue? I'm having the same problem, maybe I'm making the same error.
