### ISSUE TITLE
Downloading and uploading

### ISSUE THREAD

**Issue by kieran82** [kunalvarma05/dropbox-php-sdk#68]
I only started using this new api v2 today and whated to know if there is a way to upload and download together in the same script php page. I have run ning suucessfully just not together in the same file. 
this is my test script so far 
`	//Configure Dropbox Application
	$app = new Kunnu\Dropbox\DropboxApp(DXKEY, DXSECRET, DXTOKEN);
	
	//Configure Dropbox service
	$dropbox = new Kunnu\Dropbox\Dropbox($app);
	$dropbox->download("/Software Sharing/Vessel Usernames.xlsx", './Vessel_usernames.xlsx');

	$dropboxFile = new Kunnu\Dropbox\DropboxFile("./Vessel_usernames.xlsx");
	$dropbox->simpleUpload(new Kunnu\Dropbox\DropboxFile("./Vessel_usernames.xlsx"), "/Software Sharing/Vessel_Usernames.xlsx", ['autorename' => true]);`

**Comment by kunalvarma05** [comment]
Although I'm unable to 
Try this:

```php	
//Configure Dropbox Application
$app = new Kunnu\Dropbox\DropboxApp(DXKEY, DXSECRET, DXTOKEN);

//Configure Dropbox service
$dropbox = new Kunnu\Dropbox\Dropbox($app);
// Local file
$dropboxFile = new Kunnu\Dropbox\DropboxFile("./Vessel_usernames.xlsx"); 

// Download the File
$dropbox->download("/Software Sharing/Vessel Usernames.xlsx", $dropboxFile);

// Upload the file
$dropbox->simpleUpload($dropboxFile, "/Software Sharing/Vessel_Usernames.xlsx", ['autorename' => true]);
```

**Comment by kieran82** [comment]
Thanks that worked great for me
