### ISSUE TITLE
PHP Fatal error:  Class 'Kunnu\Dropbox\Http\Clients\DropboxHttpClientFactory' not found

### ISSUE THREAD

**Issue by willihangga** [kunalvarma05/dropbox-php-sdk#7]
I got an error after initializing your API: 
`PHP Fatal error:  Class 'Kunnu\Dropbox\Http\Clients\DropboxHttpClientFactory' not found`
Is there anything that I missed?

**Comment by compujosh** [comment]
Did you require composer's autoload and use all the relevant namespaces?

```
use Kunnu\Dropbox\Dropbox;
use Kunnu\Dropbox\DropboxApp;
use Kunnu\Dropbox\Exceptions;
```

**Comment by willihangga** [comment]
this is my code: https://gist.github.com/19ac16d47d9579f537f0aef86156026b
I'm not using composer right now

**Comment by compujosh** [comment]
I suggest using Composer; otherwise you have to include all the files in the Dropbox directory and the subdirectories

**Comment by kunalvarma05** [comment]
@willihangga hope @compujosh sums it up. It's highly recommended that you use Composer :)

Thanks!
