### ISSUE TITLE
Can we get permanent link to file?

### ISSUE THREAD

**Issue by ogwugo** [kunalvarma05/dropbox-php-sdk#72]
$dropboxFile = new DropboxFile($file);
        $file = $dropbox->upload($dropboxFile,$name, ['autorename' => true]);
        $temporaryLink = $dropbox->getTemporaryLink($file->getPathLower());
this can return temporary link which always expire after 4hrs, I need permanent link because I want to use this on my ecommerce website to view images..

**Comment by kunalvarma05** [comment]
Dropbox does not allow serving of static assets (images/stylesheets) directly ([More details here](https://webapps.stackexchange.com/a/106293)). 

However, you can [create a shared link](https://www.dropbox.com/developers/documentation/http/documentation#sharing-create_shared_link_with_settings) and you would get a url to the file in the response. Now that URL would contain a parameter in the end like so: `dl=0`, which will render the Dropbox's file viewer.  But if you go to the same URL with the parameter changed to `dl=1`, your browser will initiate a download. 

Here's how you would do it using the SDK:

```php
/**
* Assuming you have configured the DropboxApp class
* @see https://github.com/kunalvarma05/dropbox-php-sdk/wiki/Configuration
*/
$dropbox = new Dropbox($app);
$pathToFile = "/product-image.jpg";

$response = $dropbox->postToAPI("/sharing/create_shared_link_with_settings", [
    "path" => $pathToFile
]);

$data = $response->getDecodedBody();
$url = $data['url'];

// Suppose value of $url is: 
// https://www.dropbox.com/s/2sn712vy1ovegw8/product-image.jpg?dl=0

// Change the value of `dl` parameter to 1.
// We're overwriting the parameter by appending it 
// with a different value (1). Since Dropbox will use the later's value.
// This is a dirty way, though.
// See: https://stackoverflow.com/a/5809881
$url .= "&dl=0";
// https://www.dropbox.com/s/2sn712vy1ovegw8/product-image.jpg?dl=0&dl=1

echo "<img src='" + $url + "'>";
```

See: [Working with Shared folders and Links](https://github.com/kunalvarma05/dropbox-php-sdk/wiki/Working-with-Shared-Links-Folders)
