### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by Krupaly2k** [kunalvarma05/dropbox-php-sdk#75]
Hi,

I need a quick help on this. Please let me know how can I use it for displaying dropbox files as I was using V1 before.

**Comment by Krupaly2k** [comment]
I am facing below issue Fatal error: Class 'PHPUnit\Framework\TestCase' not found in C:\xampp\htdocs\dropbox-php-sdk-master\tests\DropboxTest.php on line 5

**Comment by kunalvarma05** [comment]
Can you be more specific as to when do you face this error, under what scenario? 

Also, have you run `composer install`?

**Comment by kunalvarma05** [comment]
Duplicate of #72
