### ISSUE TITLE
How to validate the access token

### ISSUE THREAD

**Issue by adrian2020** [kunalvarma05/dropbox-php-sdk#76]
I am a new user to Github and not sure if this is the correct forum to place queries, but here goes.
I can list, upload and download files using a stored access token, that I have generated via a login page as per your wiki.

require_once 'header.php';
if (isset($_GET['code']) && isset($_GET['state'])) {    
    //Bad practice! No input sanitization!
    $code = $_GET['code'];
    $state = $_GET['state'];

    //Fetch the AccessToken
    $accessToken = $authHelper->getAccessToken($code, $state, $callbackUrl);
	#echo "<pre>"; print_r($accessToken); echo "</pre>";
    $access_token =  $accessToken->getToken();
}

In the case of a new start or my stored is invalid , is there a method to test the token ?

Currently, I just get an untrapped error:
Fatal error: Uncaught GuzzleHttp\Exception\ServerException: Server error: `POST https://api.dropboxapi.com/2/files/list_folder` resulted in a `500 Internal Server Error`

thanks
AdrianD

**Comment by kunalvarma05** [comment]
Unfortunately, Dropbox does not provide any way (API Call or Expiration Time while issuing a Token) to validate an already obtained Access Token. 

However, according to their [Developer Support page](https://www.dropbox.com/developers/support#token-expiration):

> App access tokens effectively don't expire, but users can manually revoke tokens...
> 
> You should only process the authorization once, and save the access token for all future calls for that user. If an existing access token is invalid, (in which cases calls will return 401), you should prompt the user to re-authorize your app.

Thus, you use the Access Token you've stored and if any call to the API results in an error or an exception being thrown, you can execute the (Re) [Authorization process](https://github.com/kunalvarma05/dropbox-php-sdk/wiki/Authentication-and-Authorization).

Here's an example:

```php
// Access Token stored in Database
$accessToken = getAccessTokenFromDatabase();

// Set the Access Token
$dropbox->setAccessToken($accessToken);

// Make an API Call
try {
    $fileMetadata = $dropbox->getMetadata('/hello-world.txt');
    // ...
} catch (DropboxClientException $e) {
     // Since Dropbox returns errors encoded in JSON as strings
    // the error message needs to decoded
    $message = json_decode($e->getMessage(), true);
    // Error Type (Tag)
    $error = $message['error']['.tag'];

    // Access Token is invalid or expired
    if ($error === 'invalid_access_token') {
        // Prompt user to re-authorize
    }
}

```

The Invalid Access Token error should have it's own Exception. This will be fixed in the next minor release.

**Comment by crspybits** [comment]
While I'm not working with PHP, the closest I'm seeing to this is https://www.dropbox.com/developers/documentation/http/documentation#users-get_account but you also have to have an account id.

**Comment by tudders** [comment]
Hey there. This is still an issue for me. If an app folder is deleted on the dropbox side, the token is automatically voided along with it. All calls made with it produce a fatal error. Is there anything in the library that will change guzzle error handling to something less severe so there error can be handled without bring everything else to it's knees?

Error:

Fatal error: Uncaught GuzzleHttp\Exception\ClientException: Client error: `POST https://api.dropboxapi.com/2/files/get_metadata` resulted in a `401 Unauthorized` response: {"error_summary": "invalid_access_token/..", "error": {".tag": "invalid_access_token"}} in C:\inetpub\wwwroot\PROD\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php:113 Stack trace: #0 C:\inetpub\wwwroot\PROD\vendor\guzzlehttp\guzzle\src\Middleware.php(66): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response)) #1 C:\inetpub\wwwroot\PROD\vendor\guzzlehttp\promises\src\Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response)) #2 C:\inetpub\wwwroot\PROD\vendor\guzzlehttp\promises\src\Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array) #3 C:\inetpub\wwwroot\PROD\vendor\guzzlehttp\promises\src\TaskQueue.php(47): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}() #4 C:\inetpub\wwwroot\PROD\vendor in C:\inetpub\wwwroot\PROD\vendor\kunalvarma05\dropbox-php-sdk\src\Dropbox\Http\Clients\DropboxGuzzleHttpClient.php on line 59
