### ISSUE TITLE
getMetadata() not including deleted files/folders.

### ISSUE THREAD

**Issue by wagnered** [kunalvarma05/dropbox-php-sdk#78]
Only non-deleted folders/files are displayed. The command I'm using is:

`$metadata = $dropbox->getMetadata($subpath, array("include_deleted" => true));`

$subpath is not the root folder.

Is the option "include_deleted" => true correct?  I used what was indicated in the HTML guide.

Thank for any ideas...
Ernie D......

**Comment by kunalvarma05** [comment]
Unable to reproduce this. The `getMetadata()` method with the `['include_deleted' => true]` works as expected. Are you sure this file wasn't permanently deleted, because it wouldn't return the file in that case even if you pass the `include_deleted` param.

**Comment by wagnered** [comment]
Thank you for the feedback.  You are probably correct, but I decided to change the logic a bit so I'll close for now and re-open later if needed..

Thanks again.
