### ISSUE TITLE
composer version conflict

### ISSUE THREAD

**Issue by anurag0583** [kunalvarma05/dropbox-php-sdk#79]
It seems there is a composer lock in repo. While installing, I get following error:

Problem 1
    - Installation request for kunalvarma05/dropbox-php-sdk dev-master -> satisfiable by kunalvarma05/dropbox-php-sdk[dev-master].
    - Can only install one of: kunalvarma05/dropbox-php-sdk[v0.2.1, dev-master].
    - Installation request for kunalvarma05/dropbox-php-sdk ^0.2.1 -> satisfiable by kunalvarma05/dropbox-php-sdk[v0.2.1].

Any clue?

Thanks in advance

**Comment by kunalvarma05** [comment]
Unable to reproduce this. Can you share your `composer.json` file? 

Also, try running `composer update`.
