### ISSUE TITLE
Doesn't work with the code flow without redirect

### ISSUE THREAD

**Issue by Spreeuw** [kunalvarma05/dropbox-php-sdk#8]
It's currently not possible to use the `code` authentication flow without a redirect:

```php
    $dropbox = new Dropbox($app);
    $authHelper = $dropbox->getAuthHelper();
    $authUrl = $authHelper->getAuthUrl('');
```

Visiting the authUrl, Dropbox gives an error, saying that redirect_url can't be empty. Removing the redirect_url parameter from the url fixes the issue.

The `getAccessToken` function also expects a $state parameter, which is not available when doing this without a redirect (afaik).

**Comment by kunalvarma05** [comment]
@Spreeuw I'll look into it.

Thanks!

**Comment by kunalvarma05** [comment]
@Spreeuw You can now call `getAuthUrl()` without passing in a redirect_url. According to Dropbox:

> A redirect URI is required for the token flow, but optional for the code flow. If the redirect URI is omitted, the code will be presented directly to the user and they will be invited to enter the information in your app.

So now, `$authHelper->getAuthUrl();` should work.

Thanks for pointing this out!
