### ISSUE TITLE
Check if file exists.

### ISSUE THREAD

**Issue by hkonnet** [kunalvarma05/dropbox-php-sdk#81]
How can we check if a file exists in a dropbox location should getMetadata method be used or any other efficient way?

**Comment by kunalvarma05** [comment]
The [`getMetadata()`](https://github.com/kunalvarma05/dropbox-php-sdk/wiki/Working-with-files#get-filefolder-metadata) method is easiest and probably the only reliable way to check if a file or folder exists. Dropbox doesn't have a dedicated endpoint for this.

See: https://www.dropbox.com/developers/documentation/http/documentation

**Comment by toddalbert** [comment]
@kunalvarma05 This throws a fatal error, though if the file doesn't exist.

**Comment by hkonnet** [comment]
@toddalbert Actually it throws an exception when the file is not found you have to use **try, catch** for that..
