### ISSUE TITLE
Class 'Kunnu\Dropbox\DropboxApp' not found

### ISSUE THREAD

**Issue by TranBa92** [kunalvarma05/dropbox-php-sdk#86]
Currently migrating API v1 to v2, and I'm having a hard time on uploading a file and receiving an error.

Error:
127.0.0.1:39086 [500]: /dropbox-php-sdk/upload.php - Class 'Kunnu\Dropbox\DropboxApp' not found in /var/www/html/dropbox-php-sdk/upload.php on line 18

**Comment by VolCh** [comment]
What about something like `require '../vendor/autoload.php';` in upload.php? Do you use composer autoload?

**Comment by TranBa92** [comment]
Thanks you
