### ISSUE TITLE
{"error_summary": "invalid_access_token/..", "error": {".tag": "invalid_access_token"}}

### ISSUE THREAD

**Issue by TranBa92** [kunalvarma05/dropbox-php-sdk#87]
DropboxClientException in DropboxGuzzleHttpClient.php line 59:
{"error_summary": "invalid_access_token/..", "error": {".tag": "invalid_access_token"}}.

Thanks

**Comment by kunalvarma05** [comment]
Are you sure the Access Token you're using is valid? Also, are you obtaining the Access token using the OAuth2 process or directly using the generated one?

Please share some more information.
