### ISSUE TITLE
How to upload pictures into a folder ?

### ISSUE THREAD

**Issue by TranBa92** [kunalvarma05/dropbox-php-sdk#88]
$app = new DropboxApp("xxx", "xxx","xxx");
            $dropbox = new Dropbox($app);
            $filename = '/'.time().'_'.str_replace(' ', '', $request->file('fileImage')->getClientOriginalName());
            $destinationPath = 'uploads/tmp_chiphi/';
            $request->file('fileImage')->move($destinationPath,$filename);
            $dropboxFile = new DropboxFile(public_path('uploads/tmp_chiphi' . $filename));
            $file = $dropbox->upload($dropboxFile,$filename, ['autorename' => true]);

My code has run oke, Now I want to get link to view successfully uploaded file on Dropbox.Thanks you

**Comment by kunalvarma05** [comment]
**See #72 and #65** 

Duplicate of #72 , #65

**Comment by TranBa92** [comment]
Thanks you
