### ISSUE TITLE
uploaded file size 0 bytes

### ISSUE THREAD

**Issue by Dileep-Hegde** [kunalvarma05/dropbox-php-sdk#89]
I made an Dropbox API for my project. while uploading any file from my host , the file was uploaded as empty file.
and I need more detail on dropboxFile file path specification. how to take full path of the file from the web.
I guess it is not writing the file because dropbox API v1 has Writemode but here its not.

**Comment by kunalvarma05** [comment]
According to [Dropbox's API Documentation](https://www.dropbox.com/developers/documentation/http/documentation#files-upload), the default mode is `add`. 

Please share more information, preferably the code block.

**Comment by Dileep-Hegde** [comment]
I m working on project in ubuntu. when i upload and download via localhost using xampp/lampp it works.
But in web host only the files located in opt/lampp/htdocs/ works , for any other file the host web page or a image file shows 'This page isn’t working'.

here is my code.
` if (isset($_POST["file"])) {
    $file = $_POST['file'];

$dropboxFile = new DropboxFile($file);

$files = $dropbox->upload($dropboxFile, "/".$file, ['autorename' => true]);`

i tried to change DropboxFile param but same error  'This page isn’t working'.

**Comment by Dileep-Hegde** [comment]
can u explain how to dynamically take the **file from any location of local storage** and upload it to dropbox using **live server ( not  local host )**

**Comment by kunalvarma05** [comment]
I'm not sure I understand the question. What do you mean by local storage? 

From what I understand (quite limited), you want to upload a user's uploaded file to Dropbox. The code you're using seems to be incorrect. Here's how you can handle file uploads:

```php
// File: upload.php

// Configure and instantiate the Dropbox class
// ...

if (isset($_FILES["file"])) {
    // File to Upload
    $file = $_FILES['file'];

    // File details
    $fileName = $file['name'];
    $filePath = $file['tmp_name'];

    // Create stream from temporary file path
    $stream = fopen($filePath, "r");

    // Create Dropbox File from Stream
    $dropboxFile = DropboxFile::createByStream($fileName, $stream);

    // Upload the file to Dropbox
    $uploadedFile = $dropbox->upload($dropboxFile, "/" . $fileName, ['autorename' => true]);
} 
```

Your HTML form could be something like this:
```html
<form action="upload.php" method="POST" enctype="multipart/form-data">
    <input type="file" name="file">
    <button type="submit">Upload</button>
</form>
```

**Comment by Dileep-Hegde** [comment]
Unfortunately code didn't worked . gives http 500 error.
