### ISSUE TITLE
Can you please add some more sample code in the documentation?

### ISSUE THREAD

**Issue by sioakim** [kunalvarma05/dropbox-php-sdk#9]
Can you please add some more sample code in the documentation on how to call different methods?

Specifically I want to create a full file listing of my Dropbox files recursively as an output e.g.:
/File.txt
/Folder1/File2.txt
/Folder1/File3.txt
/Folder2/File4.txt

That would mean that I need to get the listing, detect what is folder or file and call different(?) functions to get the location and filename.

Thanks a lot!

**Comment by kunalvarma05** [comment]
Absolutely.

**Comment by fkhateeb** [comment]
I have solved this like this  
`  if (get_class($item) === 'Kunnu\Dropbox\Models\DeletedMetadata') { }
if (get_class($item) === 'Kunnu\Dropbox\Models\FileMetadata') {}`
 So I can know the type of the file and use it's special functions.

**Comment by kunalvarma05** [comment]
@fkhateeb This is a duplicate of #19

**Comment by DaveChild** [comment]
In case anyone else is looking a way to list the folder recursively (for example if upgrading from the V1 API getDelta method), the solution is to pass an addition param through to the request, like this:

`$listFolderContents = $dropbox->listFolder("/", ['recursive' => true]);`
