### ISSUE TITLE
more info needed on path of file

### ISSUE THREAD

**Issue by Dileep-Hegde** [kunalvarma05/dropbox-php-sdk#91]
```
if (isset($_POST['file'])) {
    $file = $_POST['file'];

$files = $dropbox->download("/".$file);

//File Contents
$contents = $files->getContents();

//Save file contents to disk
file_put_contents(__DIR__."/".$file , $contents);
```

the downloaded file stored in my own web host storage. how to direclty made it available as downloadable file to user local storage.

**Comment by kunalvarma05** [comment]
I'm not sure I understand you question completely or if it is related to the SDK. What exactly are you trying to achieve?

**Comment by Dileep-Hegde** [comment]
How to download dropbox file directly ?
How to get the contents of dropbox in html form like user has to select file which is in Dropbox to download?

I achieved downloading by alternative way like
First i installed dropbox and selected file which is there in local dropbox folder to get the file name then downloaded file from dropbox to my host storage  and then using php downloaded that file from host storage to local storage.

I mean 
//Save file contents to disk
file_put_contents(__DIR__ . "/logo.png", $contents);
Saves file to web storage 

And how to get the list or contents of dropbox?

**Comment by kunalvarma05** [comment]
Use the [`listFolderContents()`](https://github.com/kunalvarma05/dropbox-php-sdk/wiki/Working-with-files#list-folder-contents) method to retrieve a list of all files.

If you want to download the file to your server and then provide the user a link to download the file from the server, use the [`download()`](url).

If you want to provide a direct download link to the user, [create and user a shared link to the file](https://github.com/kunalvarma05/dropbox-php-sdk/wiki/Working-with-Shared-Links-Folders).
