### ISSUE TITLE
Adding additional headers to post operation

### ISSUE THREAD

**Issue by jamesmbowler** [kunalvarma05/dropbox-php-sdk#96]
I'm uploading a file to a business account, so I need to add a header

'Dropbox-Api-Select-User'=> DROPBOX_MEMBER_ID

Here's the error, fyi:
Error in call to API function "files/upload": This API function operates on a single Dropbox account, but the OAuth 2 access token you provided is for an entire Dropbox Business team.  Since your API app key has team member file access permissions, you can operate on a team member's Dropbox by providing the "Dropbox-API-Select-User" HTTP header or "select_user" URL parameter to specify the exact user <https://www.dropbox.com/developers/documentation/http/teams>.

Is there a good way to add a header to a file upload?

**Comment by kunalvarma05** [comment]
Additional headers cannot be added if you're using the API methods directly ([`upload()` ](https://github.com/kunalvarma05/dropbox-php-sdk/blob/master/src/Dropbox/Dropbox.php#L773) in your case). However, you can create a [`DropboxRequest`](https://github.com/kunalvarma05/dropbox-php-sdk/blob/master/src/Dropbox/DropboxRequest.php) object including any headers (`Dropbox-Api-Select-User`) you wish to send along with the request, either through the constructor or the [`setHeaders()`](https://github.com/kunalvarma05/dropbox-php-sdk/blob/master/src/Dropbox/DropboxRequest.php#L242) method.

Then, send the `DropboxRequest` object directly through the [`sendRequest()`](https://github.com/kunalvarma05/dropbox-php-sdk/blob/master/src/Dropbox/DropboxClient.php#L146) method on the `DropboxClient` class's object, which can be obtained from the `Dropbox` class's object by calling the [`getClient()`](https://github.com/kunalvarma05/dropbox-php-sdk/blob/master/src/Dropbox/Dropbox.php#L176) method.

Here's how you can achieve the above:

```php
// Dropbox
$dropbox = new Dropbox(..);

//Access Token
$accessToken = "you-access-token";

//Make Dropbox File
$dropboxFile = $this->makeDropboxFile("/path-to-your-file.txt");

// Path on Dropbox to upload the file to
$path = "/my-folder"

//Set the path and file
$params = ['path' => $path, 'file' => $dropboxFile];

// Custom Headers
$headers = ['Dropbox-Api-Select-User'=> 'DROPBOX_MEMBER_ID'];

//Make a DropboxRequest object
$request = new DropboxRequest("POST", "/files/upload", $accessToken, "content", $params, $headers);

//Send Request through the DropboxClient
//Fetch the DropboxResponse
$dropboxResponse = $dropbox->getClient()->sendRequest($request);
// @see https://github.com/kunalvarma05/dropbox-php-sdk/blob/master/src/Dropbox/DropboxResponse.php
$body = $dropboxResponse->getDecodedBody();

//Make and the Model
$fileMetadata = new FileMetadata($body);
```

**Comment by jamesmbowler** [comment]
Works! Thanks so much.
